version: '3.7'

services:
  currency-exchange:
    image: wilsonfer31/mmv2-currency-exchange-service:currency-exchange-service
    mem_limit: 700m
    ports: 
     - "8000:8000"
    networks:
     - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  currency-conversion:
    image: wilsonfer31/mmv2-currency-conversion-service:currency-conversion-service
    mem_limit: 700m
    ports: 
     - "8100:8100"
    networks:
     - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  
  api-gateway:
    image: wilsonfer31/mmv2-api-gateway:api-gateway
    mem_limit: 700m
    ports: 
     - "8765:8765"
    networks:
     - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans


  naming-server:
    image: wilsonfer31/mmv2-naming-server:naming-server
    mem_limit: 700m
    ports: 
     - "8761:8761"
    networks:
     - currency-network


     
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: always 

networks:
  currency-network: