insert into CURRENCY_EXCHANGE
(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE ,ENVRIRONMENT)
VALUES (10001,'USD','INR',65,'');
insert into CURRENCY_EXCHANGE
(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE ,ENVRIRONMENT)
VALUES (10002,'EUR','INR',75,'');
insert into CURRENCY_EXCHANGE
(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE ,ENVRIRONMENT)
VALUES (10003,'AUD','INR',25,'');